# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        ghidra:
          - "11.3"
          - "11.2.1"
          - "11.2"
          - "11.1.2"
          - "11.1.1"
          - "11.1"
          - "11.0.3"
          - "11.0.2"
          - "11.0.1"
          - "11.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Ghidra
      uses: antoniovazquezblanco/setup-ghidra@v2.0.6
      with:
        version: ${{ matrix.ghidra }}

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.5'

    - name: Build with Gradle Wrapper
      run: gradle buildExtension
      working-directory: ./GhidraR2Web

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GhidraR2Web_Ghidra_${{ matrix.ghidra }}
        path: GhidraR2Web/dist/*.zip

  release:
    runs-on: "ubuntu-latest"
    needs: build

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4

    - name: Release 
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          GhidraR2Web_Ghidra_*/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
